version: 2
jobs:
  eslint:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: "ESLint Test - #escuelajs"
          command: yarn lint
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: "Compilar Proyecto - #escuelajs"
          command: yarn build
workflows:
  version: 2
  test_and_build:
    jobs:
      - eslint
      - build:
          requires:
            - eslint
